<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>46bbe23b-e987-4755-b15e-c96d37358403</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alkiman.Application\Alkiman.Application.csproj" />
    <ProjectReference Include="..\Alkiman.Infrastructure\Alkiman.Infrastructure.csproj" />
    <ProjectReference Include="..\Alkiman.Domain\Alkiman.Domain.csproj" />
  </ItemGroup>

</Project>
